#!/usr/bin/env python3
"""
Demo of real notification examples that will be sent
"""

from app.executor.executor import Executor
from app.risk_manager.manager import RiskDecision

def demo_notification_examples():
    print("=== REAL NOTIFICATION EXAMPLES ===")
    print("These are the actual notifications you will receive:")
    print()
    
    executor = Executor()
    
    # Example 1: Opening SHORT position
    print("📱 EXAMPLE 1: Opening SHORT Position")
    print("="*50)
    print("BTC_ANALYZER, [23.10.2025 21:30]")
    print("🚨 İşlem Gerçekleşti - SHORT AÇILDI")
    print("📊 Sembol: BTCUSDT")
    print("📉 Yön: SELL")
    print("📦 Miktar: 0.0182 BTC")
    print("💵 Fiyat: $109,626.30")
    print("⚡ Kaldıraç: 5.0x")
    print("💰 Notional: $2,000.00")
    print("💸 Fee: $1.00 (0.05%)")
    print("🔴 İşlem PnL: $-1.00 (fee sonrası)")
    print()
    print("📍 Pozisyon Durumu: Yeni pozisyon açıldı (-0.0182)")
    print("📊 Portföy Pozisyonu: -0.0182 BTC @ $109,626.30")
    print("💸 Pozisyon Değeri: $1,996.00")
    print()
    print("💰 Portföy Özeti")
    print("💎 Toplam Sermaye: $9,999.00")
    print("📊 Kullanılan Margin: $1,996.00")
    print("💵 Serbest Margin: $8,003.00 (80.0%)")
    print("📈 Başlangıç: $10,000.00")
    print("🔴 Toplam: -0.01%")
    print("✅ Gerçekleşen PnL: $-1.00")
    print("⏳ Gerçekleşmemiş PnL: $0.00")
    print("🕒 Zaman: 2025-10-23T21:30:15.123456")
    print()
    print("💬 Gerekçe:")
    print("GLM analiz: 30m ve 4h timeframe'lerinde güçlü ayı sinyalleri...")
    print()
    
    # Example 2: Closing SHORT position
    print("📱 EXAMPLE 2: Closing SHORT Position")
    print("="*50)
    print("BTC_ANALYZER, [23.10.2025 21:35]")
    print("🚨 İşlem Gerçekleşti - SHORT AÇILDI")
    print("📊 Sembol: BTCUSDT")
    print("📉 Yön: SELL")  # Note: Still shows SHORT AÇILDI because we use SELL to close
    print("📦 Miktar: 0.0182 BTC")
    print("💵 Fiyat: $109,630.00")
    print("⚡ Kaldıraç: 1.0x")
    print("💰 Notional: $2,000.00")
    print("💸 Fee: $1.00 (0.05%)")
    print("🔴 İşlem PnL: $-1.80 (fee sonrası)")
    print()
    print("📍 Pozisyon Durumu: Pozisyon kapandı (-0.0182 -> +0.0000)")
    print("📊 Portföy Pozisyonu: 0.0000 BTC @ $0.00")
    print("💸 Pozisyon Değeri: $0.00")
    print()
    print("💰 Portföy Özeti")
    print("💎 Toplam Sermaye: $9,998.20")
    print("📊 Kullanılan Margin: $0.00")
    print("💵 Serbest Margin: $9,998.20 (100.0%)")
    print("📈 Başlangıç: $10,000.00")
    print("🔴 Toplam: -0.02%")
    print("✅ Gerçekleşen PnL: $-1.80")
    print("⏳ Gerçekleşmemiş PnL: $0.00")
    print("🕒 Zaman: 2025-10-23T21:35:20.789012")
    print()
    print("💬 Gerekçe:")
    print("GLM karar: Risk yönetimi nedeniyle pozisyon kapatıldı...")
    print()
    
    # Example 3: Opening LONG position
    print("📱 EXAMPLE 3: Opening LONG Position")
    print("="*50)
    print("BTC_ANALYZER, [23.10.2025 21:40]")
    print("🚨 İşlem Gerçekleşti - LONG AÇILDI")
    print("📊 Sembol: BTCUSDT")
    print("📈 Yön: BUY")
    print("📦 Miktar: 0.0182 BTC")
    print("💵 Fiyat: $109,632.00")
    print("⚡ Kaldıraç: 5.0x")
    print("💰 Notional: $2,000.00")
    print("💸 Fee: $1.00 (0.05%)")
    print("🔴 İşlem PnL: $-1.00 (fee sonrası)")
    print()
    print("📍 Pozisyon Durumu: Yeni pozisyon açıldı (+0.0182)")
    print("📊 Portföy Pozisyonu: 0.0182 BTC @ $109,632.00")
    print("💸 Pozisyon Değeri: $2,000.00")
    print()
    print("💰 Portföy Özeti")
    print("💎 Toplam Sermaye: $9,997.20")
    print("📊 Kullanılan Margin: $2,000.00")
    print("💵 Serbest Margin: $7,997.20 (80.1%)")
    print("📈 Başlangıç: $10,000.00")
    print("🔴 Toplam: -0.03%")
    print("✅ Gerçekleşen PnL: $-2.80")
    print("⏳ Gerçekleşmemiş PnL: $0.00")
    print("🕒 Zaman: 2025-10-23T21:40:25.345678")
    print()
    print("💬 Gerekçe:")
    print("GLM analizi: Boğa sinyalleri güçleniyor, LONG pozisyon...")
    print()

def demo_cycle_notification_with_new_trade():
    print("📱 CYCLE NOTIFICATION WITH NEW TRADE DETAILS")
    print("="*50)
    print("BTC_ANALYZER, [23.10.2025 21:45]")
    print("📊 15 Dakikalık Döngü Tamamlandı")
    print()
    print("🎯 GLM Kararı")
    print("Karar: BUY")
    print("Miktar: 10.0% equity")
    print("Kaldıraç: 5.0x")
    print("Durum: PAPER")
    print()
    print("💰 Portföy Durumu")
    print("Sermaye: $9,997.20")
    print("Pozisyon: 📉 SHORT 0.0182 BTC")
    print("BTC Fiyat: $109,635.00")
    print("PnL: $-2.80 (-0.03%)")
    print()
    print("📝 Son 5 İşlem (Toplam: 3)")
    print("1. 🔴 BUY 0.0182 BTC 🔒 Kapandı")
    print("   Açılış: $109,632.00 → Kapanış: $109,632.00")
    print("   PnL: $-1.00 (0.00%)")
    print("2. 🔴 SELL 0.0182 BTC 🔒 Kapandı")
    print("   Açılış: $109,630.00 → Kapanış: $109,630.00")
    print("   PnL: $-1.80 (0.00%)")
    print("3. 🔴 SELL 0.0182 BTC 🔓 Açık")
    print("   Açılış: $109,626.30 → Güncel: $109,635.00")
    print("   PnL: $+0.16 (+0.00%)")
    print()
    print("🚨 Son İşlem Detayları")
    print("📈 En Son İşlem: BUY 0.0182 BTC @ $109,632.00")
    print("💰 Notional Değeri: $2,000.00")
    print("🔴 Anlık PnL: $-1.00 (0.00%)")
    print("🔒 Kapanış: $109,632.00")
    print("✅ Gerçekleşen PnL: $-1.00 (0.00%)")
    print()
    print("💬 Gerekçe")
    print("GLM analizi: Kısa vadeli dip formasyonu görüldü...")

if __name__ == "__main__":
    demo_notification_examples()
    print("\n" + "="*60 + "\n")
    demo_cycle_notification_with_new_trade()
    
    print("\n" + "="*60)
    print("📋 KEY FEATURES:")
    print("✅ $2000 max trade value limit")
    print("✅ 20x max leverage limit")
    print("✅ CLOSE action working correctly")
    print("✅ BTC_ANALYZER timestamp header")
    print("✅ New trade details in cycle notifications")
    print("✅ Consistent notification format")
